version: "3"

services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    env_file:
      - "./server/.env"
    command: "npm start"
    tty: true

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - PORT=3000
    tty: true
