version: "3"

services:
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - "./server/:/app/"
      - "/app/node_modules"
    env_file:
      - "./server/.env"
    command: "npm start"

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      PORT: 3000
    # command: npm install -g serve --silent && serve -s build
    tty: true

  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: social