version: '3.8'

services:
  backend:
    image: prakash20kumar/backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    networks:
      - app-network

  frontend:
    image: prakash20kumar/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
