name: Deploy MERN Stack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build \
            --build-arg MONGO_URL="${{ secrets.MONGO_URL }}" \
            --build-arg PORT="${{ secrets.BACKEND_PORT }}" \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --build-arg AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg BUCKET_NAME="${{ secrets.BUCKET_NAME }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL="${{ secrets.REACT_APP_API_URL }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Fetch EC2 Instance IP
        id: fetch_ip
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=unity-hub-web" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Accept host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Copy repository files to EC2 instance
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ env.PUBLIC_IP }}:/home/ubuntu/compose/

      - name: Deploy Docker Compose to AWS EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" > /home/ubuntu/compose/.env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> /home/ubuntu/compose/.env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> /home/ubuntu/compose/.env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> /home/ubuntu/compose/.env
            echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> /home/ubuntu/compose/.env
            echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> /home/ubuntu/compose/.env
            docker-compose -f /home/ubuntu/compose/docker-compose.yml up -d
