name: Deploy MERN Stack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend Docker image
        run: |
          docker build \
            --build-arg MONGO_URL="${{ secrets.MONGO_URL }}" \
            --build-arg PORT="${{ secrets.BACKEND_PORT }}" \
            --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --build-arg AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --build-arg AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --build-arg BUCKET_NAME="${{ secrets.BUCKET_NAME }}" \
            --build-arg REACT_APP_BASE_URL="${{ secrets.REACT_APP_BASE_URL }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./server

      - name: Build frontend Docker image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL="${{ secrets.REACT_APP_API_URL }}" \
            --build-arg REACT_APP_BASE_URL="${{ secrets.REACT_APP_BASE_URL }}" \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./client

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy using Docker Compose
        run: |
          cat << 'EOF' > docker-compose.yml
          version: '3.8'
          services:
            backend:
              image: ${{ secrets.DOCKER_USERNAME }}/backend:latest
              ports:
                - "5000:5000"
              environment:
                MONGO_URL: ${{ secrets.MONGO_URL }}
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
                REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
            frontend:
              image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
              ports:
                - "3000:3000"
              environment:
                REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          EOF
          docker-compose up -d
