name: Deploy to AWS

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Initialize Terraform with S3 backend
      run: terraform init -backend-config="bucket=social-media-aws"

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      run: terraform plan -out tfplan

    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
      env:
        TF_VAR_documentdb_username: ${{ secrets.TF_VAR_documentdb_username }}
        TF_VAR_documentdb_password: ${{ secrets.TF_VAR_documentdb_password }}

    - name: Output DocumentDB Endpoint
      id: output
      run: echo "::set-output name=documentdb_uri::$(terraform output -raw documentdb_endpoint)"
